server {
    listen 80;
    server_name localhost;

    # Hardening basico
    server_tokens off;

    # Frontend / contenido estatico
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # TODO: proxy hacia la API cuando exista el servicio api
    # location /api/ {
    #     proxy_pass http://api:3000;
    # }
}
